### PR TITLE
Use LooseVersion to compare requests versions

### LINKED ISSUE #649: Linkchecker does not work with requests 2.10.0 (fails with This program requires Python requests 2.2.0 or later.)
Trying to install linkchecker into a python 2.7 virtual env currently fails apparently do to incompatibility with the just released requests 2.10.0

See below for an installation into a fresh python 2.7 virtual env on OSX 10.11 (We have seen the same issue on Travis CI (Ubuntu 12.04)
```
(test) ✔ ~ python --version
Python 2.7.11
(test) ✔ ~ pip --version
pip 8.1.1 from /Users/jhn/Envs/test/lib/python2.7/site-packages (python 2.7)
(test) ✔ ~ pip install linkchecker
Collecting linkchecker
Collecting requests>=2.2.0 (from linkchecker)
  Using cached requests-2.10.0-py2.py3-none-any.whl
Installing collected packages: requests, linkchecker
Successfully installed linkchecker-9.3 requests-2.10.0
(test) ✔ ~ linkchecker --help
This program requires Python requests 2.2.0 or later.
(test) ✘-1 ~ pip install requests==2.9.2
Collecting requests==2.9.2
  Using cached requests-2.9.2-py2.py3-none-any.whl
Installing collected packages: requests
  Found existing installation: requests 2.10.0
    Uninstalling requests-2.10.0:
      Successfully uninstalled requests-2.10.0
Successfully installed requests-2.9.2
(test) ✔ ~ linkchecker --help
usage: linkchecker [-h] [-f FILENAME] [-t NUMBER] [-V] [--list-plugins]
                   [--stdin] [-D STRING] [-F TYPE[/ENCODING[/FILENAME]]]
                   [--no-status] [--no-warnings] [-o TYPE[/ENCODING]] [-q]
                   [-v] [--cookiefile FILENAME] [--check-extern]
                   [--ignore-url REGEX] [--no-follow-url REGEX] [-N STRING]
                   [-p] [-r NUMBER] [--timeout NUMBER] [-u STRING]
                   [--user-agent STRING]
                   [url [url ...]]
...
```

### PR DESCRIPTION
**Pull request by jenshnielsen**
This makes sure that 2.10.0 > 2.2.0 as expected. Closes #649

### CODE REVIEW

**Comment by charford** [comment]
+1 I ran into this issue today. Had to force install requests 2.9.2 instead of latest (2.10.0) to make it work in the meantime.

**Comment by astrofrog** [comment]
+1, please merge this and release again soon!

**Comment by Habbie** [comment]
Had a failing build due to this again today. Can you please consider merging this? Thank you!

**Comment by anatolykazantsev** [comment]
This is really booboo. The bug poped up in current Debian testing :-(

**Comment by mgedmin** [comment]
A different fix was committed in c2ce810c3fb00b895a841a7be6b2e78c64e7b042.

**Comment by anatolykazantsev** [comment]
@mgedmin thanks for notifying!

**Comment by anarcat** [comment]
please reroll this PR in the new organisation here: https://github.com/linkcheck/linkchecker/pulls see #686 for details

**Comment by Habbie** [comment]
Given c2ce810, shouldn't we just close this?

**Comment by anarcat** [comment]
sure but only @jenshnielsen and @wummel can do that...

**Comment by jenshnielsen** [comment]
Sure I have closed this

**Pull request closed without merging**
